export class Constants {
    static POSTGRES_HOST = 'POSTGRES_HOST'
    static POSTGRES_PORT = 'POSTGRES_PORT'
    static POSTGRES_USERNAME = 'POSTGRES_USERNAME'
    static POSTGRES_PASSWORD = 'POSTGRES_PASSWORD'
    static POSTGRES_DATABASE = 'POSTGRES_DATABASE'
    static PORT = 'PORT'
    static ENTITIES_PATH = 'ENTITIES_PATH'
    static MIGRATION_TABLE_NAME = 'MIGRATION_TABLE_NAME'
    static MIGRATIONS_FILE_PATH = 'MIGRATIONS_FILE_PATH'
    static MIGRATIONS_DIRECTORY = 'MIGRATIONS_DIRECTORY'
    static DATABASE_TYPE = 'DATABASE_TYPE'
}